const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{test}=require('node:test');
const md='# 知识树\n## LlamaIndex\n### VectorStoreIndex\n<!-- aitree-note:start -->\n## 定义\n索引负责组织检索。\n```js\n  const x = 1;\n```\n<!-- aitree-note:end -->\n> 📎 [查看对话原文](https://example.test/chat)\n### Other\n其他笔记正文。';
function runtime(){const store={knowledge_tree_md:md};let listener;const ctx=vm.createContext({URL,console,chrome:{runtime:{onMessage:{addListener(fn){listener=fn}},onInstalled:{addListener(){}}},storage:{local:{async get(k){return {[k]:store[k]}},async set(v){Object.assign(store,v)}}}}});ctx.chrome.downloads={onChanged:{addListener(){}},async search(){return [];}};ctx.importScripts=(...files)=>files.forEach(file=>vm.runInContext(fs.readFileSync(__dirname+'/../'+file,'utf8'),ctx));ctx.chrome.alarms={async create(){},async clear(){},onAlarm:{addListener(){}}};ctx.chrome.runtime.onStartup={addListener(){}};ctx.chrome.storage.onChanged={addListener(){}};vm.runInContext(fs.readFileSync(__dirname+'/../background.js','utf8'),ctx);const M=ctx.KnowledgeModel,node=M.parse(md).nodes.find(n=>n.title==='VectorStoreIndex');return {store,ctx,M,E:ctx.NoteEditor,T:vm.runInContext('Taxonomy',ctx),node,send:payload=>new Promise(resolve=>listener({type:'SAVE_NOTE',payload},{},resolve))};}
test('edit model hides only metadata and preserves Markdown/code',()=>{const r=runtime(),s=r.E.split(r.node.body);assert.ok(s.content.includes('  const x = 1;'));assert.ok(s.content.includes('## 定义'));assert.equal(s.content.includes('aitree-note'),false);assert.equal(s.sources.length,1);});
test('save updates title and body, keeps sources, backs up, and protects manual content',async()=>{const r=runtime();const result=await r.send({baseMd:md,nodeId:r.node.id,title:'向量索引',content:'## 新的小节\n⭐ 这是我补充的理解。'});assert.equal(result.status,'success');assert.equal(r.store.knowledge_tree_before_manual_edit.md,md);assert.ok(result.md.includes('https://example.test/chat'));const node=r.M.parse(result.md).nodes.find(n=>n.title==='向量索引');assert.equal(node.children.length,0);assert.ok(node.body.includes(r.E.MARKER));assert.equal(r.T.sameSource(node.body.join('\n'),'https://example.test/chat'),false);});
test('unrelated updates are merged, same-note conflicts keep current content',async()=>{const r=runtime();r.store.knowledge_tree_md=md+'\n## New Branch\nFresh data';let result=await r.send({baseMd:md,nodeId:r.node.id,title:r.node.title,content:'我的修改内容'});assert.equal(result.status,'success');assert.ok(result.md.includes('Fresh data'));const current=r.store.knowledge_tree_md;result=await r.send({baseMd:md,nodeId:r.node.id,title:r.node.title,content:'stale overwrite'});assert.equal(result.status,'error');assert.equal(r.store.knowledge_tree_md,current);});
test('duplicate renamed title is rejected without writing',async()=>{const r=runtime();const result=await r.send({baseMd:md,nodeId:r.node.id,title:'Other',content:'body'});assert.equal(result.status,'error');assert.equal(r.store.knowledge_tree_md,md);});
test('editing a directory is rejected',async()=>{const r=runtime(),node=r.M.parse(md).nodes.find(n=>n.title==='LlamaIndex');const result=await r.send({baseMd:md,nodeId:node.id,title:'LlamaIndex 学习',content:'## 目录说明\n这是我的学习记录。'});assert.equal(result.status,'error');assert.equal(r.store.knowledge_tree_md,md);});
test('same-source replacement refuses manually edited notes',async()=>{const r=runtime();await r.send({baseMd:md,nodeId:r.node.id,title:r.node.title,content:'手动整理后的重要结论。'});const s=r.T.snapshot(r.store.knowledge_tree_md),note=s.records.find(n=>n.node.title==='VectorStoreIndex');assert.throws(()=>r.T.apply(r.store.knowledge_tree_md,{technology:'LlamaIndex'},[{heading:'New',content:'LLM overwrite attempt content.',replaces:[note.id]}],[{id:note.id,path:note.path,content:note.node.body.join('\n')}],{placements:[{index:0,path:['LlamaIndex']}],moves:[]},'https://example.test/chat'),/同源/);});
test('reserved text and source syntax inside code remain editable code',()=>{const r=runtime(),s=r.E.split(['```html',r.E.MARKER,'> 📎 [查看对话原文](https://code.test)','```']);assert.equal(s.sources.length,0);assert.ok(s.content.includes(r.E.MARKER));});
test('no-op save does not replace the backup',async()=>{const r=runtime();const result=await r.send({baseMd:md,nodeId:r.node.id,title:r.node.title,content:r.E.split(r.node.body).content});assert.equal(result.changed,false);assert.equal(r.store.knowledge_tree_before_manual_edit,undefined);});
